export const products = [
  {
    id: 1,
    title: "Crash Bandicoot N. Sane Trilogy",
    price: 179.99,
    rating: 5,
    tag: "Remaster",
    image: "/assets/crash/crash_n_sane_trilogy.jpg",
  },
  {
    id: 2,
    title: "Crash Bandicoot 4: It's About Time",
    price: 249.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/crash/crash_4.jpg",
  },
  {
    id: 3,
    title: "Crash Team Racing Nitro-Fueled",
    price: 199.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/crash/crash_racing.jpg",
  },
  {
    id: 4,
    title: "Crash Bandicoot: The Wrath of Cortex",
    price: 149.99,
    rating: 3,
    tag: "Clássico",
    image: "/assets/crash/crash_wrath.jpg",
  },
  {
    id: 5,
    title: "Crash Bash",
    price: 129.99,
    rating: 4,
    tag: "Party",
    image: "/assets/crash/crash_bash.jpg",
  },
  {
    id: 6,
    title: "Crash Bandicoot Bundle Collection",
    price: 399.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/crash/crash_bundle.jpg",
  },
];
