export const products = [
  {
    id: 1,
    title: "Dark Souls: Prepare to Die Edition",
    price: 199.99,
    rating: 5,
    tag: "Clássico",
    image: "/assets/dark_souls_1.webp",
  },
  {
    id: 2,
    title: "Dark Souls II: Scholar of the First Sin",
    price: 179.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/dark_souls_2.webp",
  },
  {
    id: 3,
    title: "Dark Souls III: The Fire Fades Edition",
    price: 219.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/dark_souls_3.webp",
  },
  {
    id: 4,
    title: "Demon Souls Remake",
    price: 189.99,
    rating: 5,
    tag: "Remake",
    image: "/assets/Demons_Souls_remake_cover_art.webp",
  },
  {
    id: 5,
    title: "Elden Ring",
    price: 499.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/Elden_Ring_capa.webp",
  },
  {
    id: 6,
    title: "Sekiro",
    price: 159.99,
    rating: 4,
    tag: "Promoção",
    image: "/assets/Sekiro_art.webp",
  },
];
