export const products = [
  {
    id: 1,
    title: "Dark Souls: Prepare to Die Edition",
    price: 199.99,
    rating: 5,
    tag: "Clássico",
    image: "/assets/dark_souls/dark_souls_1.jpg",
  },
  {
    id: 2,
    title: "Dark Souls II: Scholar of the First Sin",
    price: 179.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/dark_souls/dark_souls_2.jpg",
  },
  {
    id: 3,
    title: "Dark Souls III: The Fire Fades Edition",
    price: 219.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/dark_souls/dark_souls_3.jpg",
  },
  {
    id: 4,
    title: "Dark Souls Remastered",
    price: 189.99,
    rating: 5,
    tag: "Remaster",
    image: "/assets/dark_souls/dark_souls_remastered.jpg",
  },
  {
    id: 5,
    title: "Dark Souls Trilogy Box Set",
    price: 499.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/dark_souls/dark_souls_trilogy.jpg",
  },
  {
    id: 6,
    title: "Dark Souls Artorias of the Abyss",
    price: 159.99,
    rating: 4,
    tag: "DLC",
    image: "/assets/dark_souls/dark_souls_dlc.jpg",
  },
];
