export const products = [
  {
    id: 1,
    title: "Final Fantasy VII Rebirth",
    price: 349.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/final_fantasy/Final_Fantasy_7_Rebirth_capa.png",
  },
  {
    id: 2,
    title: "Final Fantasy XVI",
    price: 299.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/final_fantasy/Final_Fantasy_16_capa.png",
  },
  {
    id: 3,
    title: "Final Fantasy XV",
    price: 199.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/final_fantasy/Final_Fantasy_XV_capa.png",
  },
  {
    id: 4,
    title: "Final Fantasy X/X-2 HD Remaster",
    price: 159.99,
    rating: 5,
    tag: "",
    image: "/assets/final_fantasy/FFX-X-2_HD_Remaster_NA_Cover.webp",
  },
  {
    id: 5,
    title: "Final Fantasy XIII",
    price: 149.99,
    rating: 4,
    tag: "",
    image: "/assets/final_fantasy/Final_Fantasy_XIII_EU_box_art.jpg",
  },
  {
    id: 6,
    title: "Final Fantasy Collection",
    price: 399.99,
    rating: 5,
    tag: "Promo",
    image: "/assets/final_fantasy/Ffxboxart.jpg",
  },
];
