export const products = [
  {
    id: 1,
    title: "Final Fantasy VII Rebirth",
    price: 349.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/Final_Fantasy_7_Rebirth_capa.webp",
  },
  {
    id: 2,
    title: "Final Fantasy XVI",
    price: 299.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/Final_Fantasy_16_capa.webp",
  },
  {
    id: 3,
    title: "Final Fantasy XV",
    price: 199.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/Final_Fantasy_XV_capa.webp",
  },
  {
    id: 4,
    title: "Final Fantasy X/X-2 HD Remaster",
    price: 159.99,
    rating: 5,
    tag: "",
    image: "/assets/FFX-X-2_HD_Remaster_NA_Cover.webp",
  },
  {
    id: 5,
    title: "Final Fantasy XIII",
    price: 149.99,
    rating: 4,
    tag: "",
    image: "assets/Final_Fantasy_XIII_EU_box_art.webp",
  },
  {
    id: 6,
    title: "Final Fantasy XII: The Zodiac Age",
    price: 139.99,
    rating: 5,
    tag: "",
    image: "/assets/Final_Fantasy_XII_Box_Art.webp",
  },
  {
    id: 7,
    title: "Final Fantasy IX",
    price: 99.99,
    rating: 5,
    tag: "Promo",
    image: "/assets/Ffixbox.webp",
  },
  {
    id: 8,
    title: "Final Fantasy VIII",
    price: 99.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/FFVIII.webp",
  },
  {
    id: 9,
    title: "Final Fantasy VII (Original)",
    price: 89.99,
    rating: 5,
    tag: "",
    image: "/assets/Final_Fantasy_VII_Box_Art.webp",
  },
  {
    id: 10,
    title: "Final Fantasy I-VI Pixel Remaster",
    price: 249.99,
    rating: 5,
    tag: "Novo",
    image: "/assets/Final Fantasy I-VI Pixel Remaster.webp",
  },
];
