export const products = [
  {
    id: 1,
    title: "Spyro the Dragon Reignited Trilogy",
    price: 229.99,
    rating: 5,
    tag: "Remaster",
    image: "/assets/spyro/spyro_trilogy.jpg",
  },
  {
    id: 2,
    title: "Spyro: Year of the Dragon",
    price: 179.99,
    rating: 5,
    tag: "Clássico",
    image: "/assets/spyro/spyro_year_dragon.jpg",
  },
  {
    id: 3,
    title: "Spyro: Ripto's Rage!",
    price: 169.99,
    rating: 4,
    tag: "Promo",
    image: "/assets/spyro/spyro_ripto.jpg",
  },
  {
    id: 4,
    title: "Spyro: A Hero's Tail",
    price: 159.99,
    rating: 4,
    tag: "Aventura",
    image: "/assets/spyro/spyro_hero_tail.jpg",
  },
  {
    id: 5,
    title: "Spyro: Enter the Dragonfly",
    price: 149.99,
    rating: 3,
    tag: "",
    image: "/assets/spyro/spyro_dragonfly.jpg",
  },
  {
    id: 6,
    title: "Spyro Collector's Edition",
    price: 399.99,
    rating: 5,
    tag: "Coleção",
    image: "/assets/spyro/spyro_collection.jpg",
  },
];
